[package]
name = "flibooks-es"
version = "0.2.0"
authors = ["alxeg <alx.egorov@gmail.com>"]

[dependencies]
elastic = "^0.20.10"
clap = "^2.33.0"
config = "^0.10.1"
futures = "^0.1.29"
futures-cpupool = "^0.1.8"
inflections = "1.1.1"
itertools = "0.8.2"
lazy_static = "^1.4.0"
log = "^0.4.8"
log4rs = "^0.10.0"
serde = "^1.0.101"
serde_derive = "^1.0.101"
serde_json = "^1.0.41"
tempfile = "^3.1.0"
tokio-core = "^0.1.17"
uuid = { version = "^0.8.1", features = ["serde", "v4"] }
zip = "^0.5.3"
walkdir = "^2.2.9"
jsonpath = "^0.1.1"

## serve dependencies
iron = "^0.6.1"
router = "^0.6.0"
bodyparser = "^0.8.0"
persistent = "^0.4.0"
