[package]
name = "flibooks-es"
version = "0.1.0"
authors = ["alxeg <alx.egorov@gmail.com>"]

[dependencies]
elastic = "0.20.10"
clap = "2.32.0"
config = "0.9.0"
futures = "0.1.24"
futures-cpupool = "0.1.8"
lazy_static = "1.1.0"
log = "0.4"
log4rs = "0.8.0"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.28"
tokio-core = "0.1.17"
uuid = { version = "0.7", features = ["serde", "v4"] }
zip = "0.4"
jsonpath = "0.1.1"

## serve dependencies
iron = "0.6.0"
router = "0.6.0"
bodyparser = "0.8.0"
persistent = "0.4.0"
