version: "3.4"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - discovery.type=single-node
      - TAKE_FILE_OWNERSHIP=true
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_URL=http://elastic:9200
    ports:
      - 5601:5601
    links:
      - elastic
    networks:
      - elnet

networks:
  elnet:
