services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - node.name=opensearch
      - TAKE_FILE_OWNERSHIP=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=afsqSFq3421!
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elnet

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: dashboards
    environment:
      SERVER_NAME: dashboards
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: afsqSFq3421!
    ports:
      - 5601:5601
    links:
      - opensearch
    networks:
      - elnet

networks:
  elnet:
