log_level = "debug"
# elastic_base_url = "http://10.100.4.5:9200/flibooks"
elastic_url = "http://localhost:9200"
elastic_password = "afsqSFq3421!"
# fb2c_path = "/Users/alxeg/Work/go-misc/flibooks-es/fb2c"
fb2c_path = "./fb2c"
